directories:
  mirror_module_path: True
  removed_mirror_prefix: "./videos/"
  output: "./videos"
  raster_images: "./images/raster"
  vector_images: "./images/vector"
  pi_creature_images: "./images/pi_creature/svg"
  #sounds: "/Users/grant/3Blue1Brown Dropbox/3Blue1Brown/sounds"
  data: "./data"
  temporary_storage: "./manim_cache"
universal_import_line: "from manim_imports_ext import *"
# tex:
#   executable: "xelatex -no-pdf"
#   template_file: "ctex_template.tex"
#   intermediate_filetype: "xdv"
style:
  font: "CMU Serif"
  text_alignment: "CENTER"
  background_color: "#000000"
camera_resolutions:
  default_resolution: "4k"
file_writer_config:
  saturation: 1.5
fps: 30
window_position: UR
window_monitor: 0
full_screen: False
embed_exception_mode: "Plain"
